from tests.storage.mock_record import MockRecord
from tests.storage.mock_data_class_record_key import MockDataClassRecordKey
from tests.storage.mock_data_class_record import MockDataClassRecord
from tests.storage.mock_dict_util import MockDictUtil
