from cl.runtime_samples.storage.cl_data_class_record_sample_key import ClDataClassRecordSampleKey as \
    DataClassRecordSampleKey
from cl.runtime_samples.storage.cl_data_class_record_sample import ClDataClassRecordSample as DataClassRecordSample
